### ISSUE TITLE
As a trainer, I want to create a new session

### ISSUE THREAD

**Issue by RamyAlshurafa** [techforbetter/connect5#37]
## As a trainer I want to create a new session and fill its information
Relates #24 

 #### Acceptance criteria:
- [ ] When I'm on "Trainer dashboard" page and click the add session button, or wherever I click add button in the footer, I want it to redirect me to "Add session" page.
- [ ] When I'm on "Add session" page, I want to get a form with [date, session type, no. people invited] fields.
- [ ] When I'm on "Add session" page, and I fill something wrong, I want to get a notification with what's wrong.
- [ ] When I'm on "Add session" page, and after I fill the form and click on submit button, I want to know If my session successfully added or not by a popup modal:
  - [ ] If it successfully added, I want it to redirect me to "Sessions" page to view my new session.
  - [ ] If there is something wrong in adding the session, I want to get a "Error" page.

Important functionality this will need to include:
- [ ] If successful, store session in database in Sessions table, linking up with Users table via the user's unique id

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa I was thinking about the unique url to the survey. 

For the survey, the URL needs to send across the sessionID so we know which session they are answering questions about. 
Due to their being two surveys for the first session (pre and 1), we also need the URL to send across details about which type of survey it is. 

So I was thinking, in the surveyURL1 and surveyURL2, rather than storing the whole URL we simply store a number for the type of survey. Then the URL that we show on the page will be for example connect5.com/survey/  followed by a number which has the number of the survey first followed by the unique session id. 

So for example, if the sessionID is 893823 and it's the link for the pre-survey, the URL would be connect5.com/survey/0893823


This would make it easier for participants to copy, and also would be the easiest way in my mind to then grab the right survey and session details to populate the form. It also will make it easier for you as we generate a URL containing the session id at the same time we're creating the session. 

What do you think?

**Comment by RamyAlshurafa** [comment]
Yeah, you are right.
I agree :+1: 
But I was thinking, for creating the session in DB we need the trainer ID to store that session for that trainer, the trainer ID will come from the cookies, and we haven't authentication right now.
how can we overcome this for now, do you think is it possible to store all sessions for one trainer (static ID) and after we have a valid authentication can tackle it.

What do you think?

**Comment by thejoefriel** [comment]
Yeah that's an interesting problem. We know that in the dummy data we have one trainer whose email is johndoe@gmail.com, so for now (as long as you've built the dummy data) you can do an initial Trainer.find({email: "johndoe@gmail.com"}) to then get the trainer's details and id and use this for creating the session. So all sessions we create for now we always be for this one trainer.

Then once we have authentication, we replace this function with instead the function that would get it from the cookie instead. 

Does that make sense?

**Comment by RamyAlshurafa** [comment]
Yeah, make sense :100:
